import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Intro from "../components/company_intro";
import Solutions from "../components/solutions_card";
import Aboutus from "../components/aboutus";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>MetaTensor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Intro>Test</Intro>
      <div className="bg-mainbg">
        <Solutions className="bg-center m-5"></Solutions>
      </div>
      <div className="m-5">
        <Aboutus></Aboutus>
      </div>
    </div>
  );
}
